// -----------------------------------------------
//
// Generated by DeepSeek using the following prompt: 
// 
// "I'm using Node.js and 'rxjs'. Can you give me a bit of 
// sample code on how to create an infinite random stream 
// of integers between 1 and 100"
//


import { interval } from 'rxjs';
import { map } from 'rxjs/operators';

const delayTimeMilliseconds = 5000;

// Create an infinite stream that emits a value every 1000ms (1 second)
const randomIntegerStream = interval(delayTimeMilliseconds).pipe(
    map(() => Math.floor(Math.random() * 100) + 1) // Generate a random integer between 1 and 100
);

// Subscribe to the stream to log the random integers
randomIntegerStream.subscribe(randomNumber => {
    console.log(`Random integer: ${randomNumber}`);
});